services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: prod
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    restart: always
